### ISSUE TITLE
Handle negative numbers properly

### ISSUE THREAD

**Issue by KingOfRostov** [dnlserrano/exavier#7]
Hey @dnlserrano, thanks for your work on `exavier`! Our team'd like to give it a shot. 

We noticed that in case when the function returns negative number, e.g:

```elixir
def something(_arg1), do: -1
```
`exavier` will mutate this `-1` into `*1` and here's gonna be an error like so:
```elixir
** (CompileError): undefined function */1
```
So we fixed it in our fork in [this](https://github.com/exavier-elixir/exavier/pull/3) PR.

**Comment by dnlserrano** [comment]
Thanks for your interest in the project. Can you open a PR here as well, so we fix it upstream in the original project? 🙏
