### ISSUE TITLE
Change configuration to avoid using application configuration

### ISSUE THREAD

**Issue by devonestes** [dnlserrano/exavier#9]
Howdy!

So I decided to give this a quick try today, and it turns out that having to set configuration in a `config.exs` file is a bit of an issue since the code I'm trying to test is a library, and I don't want this config ending up in other people's applications. It would be good if this library configuration could follow the configuration guidelines set out in the documentation [here](https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration) so this problem could be avoided.

For example, I'm trying to test benchee, but we don't even have any mix config in there (for the reasons laid out by the documentation there), and it won't run at the moment without some configuration (custom mappings), so this is a big of a sticky issue for users initial experience. I think either a dotfile that can be .gitignore'd (like Credo does) or some sort of function call somewhere would be a nice place for this configuration to reside.

Thanks for the great start towards a really nice mutation testing library for our community!

**Comment by dnlserrano** [comment]
Makes sense. I'll take a look at it. Please beware this is not ready for Production usage (i.e., relying on its mutation pass rate _100%_ as part of a CI/CD system).

I've been spending more time around other stuff as of late, but I'm keen to getting back to `exavier` and giving it the love it deserves. Definitely comments coming from a good place, such as this one, make a big difference and contribute to getting back on the OSS horse. 🐴 ♥️ 

I'll keep you posted. Thanks!
